if(EXISTS "/home/johnny/git/Alex_Jan_Johannes_Mol_Sim/folder_nested_build/nested_build/tests/runtest[1]_tests.cmake")
  include("/home/johnny/git/Alex_Jan_Johannes_Mol_Sim/folder_nested_build/nested_build/tests/runtest[1]_tests.cmake")
else()
  add_test(runtest_NOT_BUILT runtest_NOT_BUILT)
endif()
